# prefixをctrl-tに変更する
set-option -g prefix C-t

# vimライクなペインの移動
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# マウスでスクロールさせる
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# setting status bar
source-file ~/.tmux/iceberg_minimal.tmux.conf
